{% set name = "spacy" %}
{% set version = "2.1.1" %}
{% set sha256sum = "809561162007bdda8a8a07cded52983e848b1a83de6dc3e8b025007bbcdb3994" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not x86_64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - msinttypes  # [win and py27]
    - python
    - setuptools
    - numpy 1.15.*
    - wheel >=0.32,<0.33
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='1.15.x') }}
      # msgpack-numpy
    - murmurhash >=0.28,<1.1.0
    - cymem >=2.0.0,<2.1.0
    - preshed >=2.0.1,<2.1.0
    - thinc >=6.12.0,<6.13.0
    - plac >=0.9.6,<1.0.0
    - pathlib  # [py27]
    - ujson >=1.35
    - dill >=0.2,<0.3
    - regex =2018.01.10
    - requests >=2.13.0,<3.0.0
    - msgpack-python >=0.5.0

test:
  requires:
    - pytest <4
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - danielfrg
