{% set version = "2.2.2" %}

package:
  name: spacy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spacy/spacy-{{ version }}.tar.gz
  sha256: 4a1b47a1af437f43987384cd6d8061f5b3e8985f0f2b323f9644ba8e733e79a4
  patches:
      patches/0002-skip-multiproc-test.patch


build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [(win and py27) or (osx and py27)]

requirements:
  build:
    - {{ compiler('cxx') }} 
  host:
    - python
    - pip
    - wheel
    - cython >=0.25
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - thinc >=7.3.0,<7.4.0
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='1.15.x') }}
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc >=7.3.0,<7.4.0
    - cython-blis >=0.4.0,<0.5.0
    - plac <1.0.0,>=0.9.6
    - requests >=2.13.0,<3.0.0
    - wasabi >=0.2.0,<1.1.0
    - srsly >=0.1.0,<1.1.0
    - jsonschema
    - pathlib >=1.0.0,<2.0.0  # [py27]
    - importlib_metadata >=0.20
 
test:
  requires:
    - pytest
    - mock
  imports:
    - spacy
  commands:
    - python -m pytest --tb=native --pyargs spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
