{% set version = "3.2.3" %}

package:
  name: spacy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spacy/spacy-{{ version }}.tar.gz
  sha256: 25d033fc07b8fbfc9bdd37b770b8a586dc414dbd603128449af32576a3891673

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - cymem >=2.0.2,<2.1.0
    - cython >=0.25,<3.0
    - cython-blis >=0.4.0,<0.8.0
    - murmurhash >=0.28.0,<1.1.0
    - numpy
    - pip
    - preshed >=3.0.2,<3.1.0
    - python
    - thinc >=8.0.12,<8.1.0
  run:
    - {{ pin_compatible('numpy') }}
    - catalogue >=2.0.6,<2.1.0
    - cymem >=2.0.2,<2.1.0
    - cython-blis >=0.4.0,<0.8.0
    - jinja2
    - langcodes >=3.2.0,<4.0.0
    - murmurhash >=0.28.0,<1.1.0
    - packaging >=20.0
    - pathy >=0.3.5
    - preshed >=3.0.2,<3.1.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.9.0
    - python
    - requests >=2.13.0,<3.0.0
    - setuptools
    - spacy-legacy >=3.0.8,<3.1.0
    - spacy-loggers >=1.0.0,<2.0.0
    - srsly >=2.4.1,<3.0.0
    - thinc >=8.0.12,<8.1.0
    - tqdm >=4.38.0,<5.0.0
    - typer >=0.3.2,<0.5.0
    - typing-extensions >=3.7.4,<4.0.0.0  # [py<=37]
    - wasabi >=0.8.1,<1.1.0

test:
  requires:
    - hypothesis
    - mock
    - pip
    - pytest-timeout
  imports:
    - spacy
  commands:
    - pip check
    - pytest -vv --tb=native --pyargs spacy -k "not beam_density"

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  dev_url: https://github.com/explosion/spaCy
  doc_url: https://spacy.io

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
